version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes: 
      - $PWD/data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

volumes:
  postgres: